"""initial migration

Revision ID: 2d9e75cd0912
Revises: 
Create Date: 2018-05-11 13:36:50.667459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d9e75cd0912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='commands')
    op.drop_index('command', table_name='commands')
    op.drop_table('commands')
    op.drop_index('name', table_name='roles')
    op.drop_column('roles', 'name')
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('name', 'roles', ['name'], unique=True)
    op.create_table('commands',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('command', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('information', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('command', 'commands', ['command'], unique=True)
    op.create_index('code', 'commands', ['code'], unique=True)
    # ### end Alembic commands ###
