"""initial migration

Revision ID: 554808b7a234
Revises: 3438581da12e
Create Date: 2018-05-15 14:33:32.522477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554808b7a234'
down_revision = '3438581da12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
