"""initial migration

Revision ID: de6c6d1160cf
Revises: ab219b81e7b7
Create Date: 2018-05-18 13:16:21.247365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6c6d1160cf'
down_revision = 'ab219b81e7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gavatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gavatar_hash')
    # ### end Alembic commands ###
